name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html pytest-asyncio playwright

    - name: Install Playwright browsers
      run: |
        python -m playwright install

    - name: Run Playwright tests
      run: |
        xvfb-run -a pytest Solutions.py --html=report.html

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html